name: r

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-h5s:
    name: ${{ matrix.os.name }} ${{ matrix.os.architecture }} ${{ matrix.os.version }} on ${{ matrix.os.host }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: openbsd
            architecture: x86-64
            version: '7.7'
            host: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash
          run: |
            sudo pkg_add hdf5
            h5dump --version
            cd src
            make test
