name: upload artifact
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - run: mkdir -p artifact
    - run: echo hello > artifact/world.txt
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: artifact/world.txt
